/*
Citrix.CloudServices.Administrators.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ccadmins

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel{}

// CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel struct for CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel
type CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel struct {
	Name string `json:"name"`
	ServiceName string `json:"serviceName"`
	DisplayName NullableString `json:"displayName,omitempty"`
	Checkable CitrixCloudServicesAdministratorsApiModelsPolicyProperty `json:"checkable"`
	ScopeChoices *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessScopeChoices `json:"scopeChoices,omitempty"`
}

type _CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel

// NewCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel instantiates a new CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel(name string, serviceName string, checkable CitrixCloudServicesAdministratorsApiModelsPolicyProperty) *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel {
	this := CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel{}
	this.Name = name
	this.ServiceName = serviceName
	this.Checkable = checkable
	return &this
}

// NewCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModelWithDefaults instantiates a new CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModelWithDefaults() *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel {
	this := CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel{}
	return &this
}

// GetName returns the Name field value
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) SetName(v string) {
	o.Name = v
}

// GetServiceName returns the ServiceName field value
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) SetServiceName(v string) {
	o.ServiceName = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetCheckable returns the Checkable field value
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetCheckable() CitrixCloudServicesAdministratorsApiModelsPolicyProperty {
	if o == nil {
		var ret CitrixCloudServicesAdministratorsApiModelsPolicyProperty
		return ret
	}

	return o.Checkable
}

// GetCheckableOk returns a tuple with the Checkable field value
// and a boolean to check if the value has been set.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetCheckableOk() (*CitrixCloudServicesAdministratorsApiModelsPolicyProperty, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Checkable, true
}

// SetCheckable sets field value
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) SetCheckable(v CitrixCloudServicesAdministratorsApiModelsPolicyProperty) {
	o.Checkable = v
}

// GetScopeChoices returns the ScopeChoices field value if set, zero value otherwise.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetScopeChoices() CitrixCloudServicesAdministratorsApiModelsAdministratorAccessScopeChoices {
	if o == nil || IsNil(o.ScopeChoices) {
		var ret CitrixCloudServicesAdministratorsApiModelsAdministratorAccessScopeChoices
		return ret
	}
	return *o.ScopeChoices
}

// GetScopeChoicesOk returns a tuple with the ScopeChoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) GetScopeChoicesOk() (*CitrixCloudServicesAdministratorsApiModelsAdministratorAccessScopeChoices, bool) {
	if o == nil || IsNil(o.ScopeChoices) {
		return nil, false
	}
	return o.ScopeChoices, true
}

// HasScopeChoices returns a boolean if a field has been set.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) HasScopeChoices() bool {
	if o != nil && !IsNil(o.ScopeChoices) {
		return true
	}

	return false
}

// SetScopeChoices gets a reference to the given CitrixCloudServicesAdministratorsApiModelsAdministratorAccessScopeChoices and assigns it to the ScopeChoices field.
func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) SetScopeChoices(v CitrixCloudServicesAdministratorsApiModelsAdministratorAccessScopeChoices) {
	o.ScopeChoices = &v
}

func (o CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["serviceName"] = o.ServiceName
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	toSerialize["checkable"] = o.Checkable
	if !IsNil(o.ScopeChoices) {
		toSerialize["scopeChoices"] = o.ScopeChoices
	}
	return toSerialize, nil
}

func (o *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"serviceName",
		"checkable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel := _CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel)

	if err != nil {
		return err
	}

	*o = CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel(varCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel)

	return err
}

type NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel struct {
	value *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel
	isSet bool
}

func (v NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) Get() *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel {
	return v.value
}

func (v *NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) Set(val *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel(val *CitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) *NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel {
	return &NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel{value: val, isSet: true}
}

func (v NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCitrixCloudServicesAdministratorsApiModelsAdministratorAccessPolicyModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


