/*
Citrix.CloudServices.Administrators.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ccadmins

import (
	"encoding/json"
)

// checks if the CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices{}

// CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices struct for CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices
type CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices struct {
	AllScopesSelected *bool `json:"allScopesSelected,omitempty"`
	Choices []CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoicesModel `json:"choices,omitempty"`
}

// NewCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices instantiates a new CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices() *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices {
	this := CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices{}
	return &this
}

// NewCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoicesWithDefaults instantiates a new CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoicesWithDefaults() *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices {
	this := CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices{}
	return &this
}

// GetAllScopesSelected returns the AllScopesSelected field value if set, zero value otherwise.
func (o *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) GetAllScopesSelected() bool {
	if o == nil || IsNil(o.AllScopesSelected) {
		var ret bool
		return ret
	}
	return *o.AllScopesSelected
}

// GetAllScopesSelectedOk returns a tuple with the AllScopesSelected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) GetAllScopesSelectedOk() (*bool, bool) {
	if o == nil || IsNil(o.AllScopesSelected) {
		return nil, false
	}
	return o.AllScopesSelected, true
}

// HasAllScopesSelected returns a boolean if a field has been set.
func (o *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) HasAllScopesSelected() bool {
	if o != nil && !IsNil(o.AllScopesSelected) {
		return true
	}

	return false
}

// SetAllScopesSelected gets a reference to the given bool and assigns it to the AllScopesSelected field.
func (o *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) SetAllScopesSelected(v bool) {
	o.AllScopesSelected = &v
}

// GetChoices returns the Choices field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) GetChoices() []CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoicesModel {
	if o == nil {
		var ret []CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoicesModel
		return ret
	}
	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) GetChoicesOk() ([]CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoicesModel, bool) {
	if o == nil || IsNil(o.Choices) {
		return nil, false
	}
	return o.Choices, true
}

// HasChoices returns a boolean if a field has been set.
func (o *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) HasChoices() bool {
	if o != nil && !IsNil(o.Choices) {
		return true
	}

	return false
}

// SetChoices gets a reference to the given []CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoicesModel and assigns it to the Choices field.
func (o *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) SetChoices(v []CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoicesModel) {
	o.Choices = v
}

func (o CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllScopesSelected) {
		toSerialize["allScopesSelected"] = o.AllScopesSelected
	}
	if o.Choices != nil {
		toSerialize["choices"] = o.Choices
	}
	return toSerialize, nil
}

type NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices struct {
	value *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices
	isSet bool
}

func (v NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) Get() *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices {
	return v.value
}

func (v *NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) Set(val *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) {
	v.value = val
	v.isSet = true
}

func (v NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) IsSet() bool {
	return v.isSet
}

func (v *NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices(val *CitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) *NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices {
	return &NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices{value: val, isSet: true}
}

func (v NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCitrixCloudServicesServiceRuntimePolicySetsModelsAdministratorAccessScopeChoices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


