/*
Citrix Virtual App & Desktop Catalog Service 147.0.26651.57932

Catalog Service

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixquickdeploy

import (
	"encoding/json"
)

// checks if the AzureVirtualNetworkGatewayMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureVirtualNetworkGatewayMetrics{}

// AzureVirtualNetworkGatewayMetrics struct for AzureVirtualNetworkGatewayMetrics
type AzureVirtualNetworkGatewayMetrics struct {
	// The average Gateway S2S bandwidth in bytes/second
	AverageBandwidth *float64 `json:"averageBandwidth,omitempty"`
	// The average tunnel bandwidth in bytes/second
	TunnelAverageBandwidth *float64 `json:"tunnelAverageBandwidth,omitempty"`
	// The average tunnel ingress bytes
	TunnelIngressBytes *float64 `json:"tunnelIngressBytes,omitempty"`
	// The average tunnel egress bytes
	TunnelEgressBytes *float64 `json:"tunnelEgressBytes,omitempty"`
	// The average tunnel egress packets
	TunnelEgressPackets *float64 `json:"tunnelEgressPackets,omitempty"`
	// The average tunnel ingress packets
	TunnelIngressPackets *float64 `json:"tunnelIngressPackets,omitempty"`
}

// NewAzureVirtualNetworkGatewayMetricsWithDefaults instantiates a new AzureVirtualNetworkGatewayMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureVirtualNetworkGatewayMetricsWithDefaults() *AzureVirtualNetworkGatewayMetrics {
	this := AzureVirtualNetworkGatewayMetrics{}
	return &this
}

// GetAverageBandwidth returns the AverageBandwidth field value if set, zero value otherwise.
func (o *AzureVirtualNetworkGatewayMetrics) GetAverageBandwidth() float64 {
	if o == nil || IsNil(o.AverageBandwidth) {
		var ret float64
		return ret
	}
	return *o.AverageBandwidth
}

// GetAverageBandwidthOk returns a tuple with the AverageBandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureVirtualNetworkGatewayMetrics) GetAverageBandwidthOk() (*float64, bool) {
	if o == nil || IsNil(o.AverageBandwidth) {
		return nil, false
	}
	return o.AverageBandwidth, true
}

// SetAverageBandwidth gets a reference to the given float64 and assigns it to the AverageBandwidth field.
func (o *AzureVirtualNetworkGatewayMetrics) SetAverageBandwidth(v float64) {
	o.AverageBandwidth = &v
}

// GetTunnelAverageBandwidth returns the TunnelAverageBandwidth field value if set, zero value otherwise.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelAverageBandwidth() float64 {
	if o == nil || IsNil(o.TunnelAverageBandwidth) {
		var ret float64
		return ret
	}
	return *o.TunnelAverageBandwidth
}

// GetTunnelAverageBandwidthOk returns a tuple with the TunnelAverageBandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelAverageBandwidthOk() (*float64, bool) {
	if o == nil || IsNil(o.TunnelAverageBandwidth) {
		return nil, false
	}
	return o.TunnelAverageBandwidth, true
}

// SetTunnelAverageBandwidth gets a reference to the given float64 and assigns it to the TunnelAverageBandwidth field.
func (o *AzureVirtualNetworkGatewayMetrics) SetTunnelAverageBandwidth(v float64) {
	o.TunnelAverageBandwidth = &v
}

// GetTunnelIngressBytes returns the TunnelIngressBytes field value if set, zero value otherwise.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelIngressBytes() float64 {
	if o == nil || IsNil(o.TunnelIngressBytes) {
		var ret float64
		return ret
	}
	return *o.TunnelIngressBytes
}

// GetTunnelIngressBytesOk returns a tuple with the TunnelIngressBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelIngressBytesOk() (*float64, bool) {
	if o == nil || IsNil(o.TunnelIngressBytes) {
		return nil, false
	}
	return o.TunnelIngressBytes, true
}

// SetTunnelIngressBytes gets a reference to the given float64 and assigns it to the TunnelIngressBytes field.
func (o *AzureVirtualNetworkGatewayMetrics) SetTunnelIngressBytes(v float64) {
	o.TunnelIngressBytes = &v
}

// GetTunnelEgressBytes returns the TunnelEgressBytes field value if set, zero value otherwise.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelEgressBytes() float64 {
	if o == nil || IsNil(o.TunnelEgressBytes) {
		var ret float64
		return ret
	}
	return *o.TunnelEgressBytes
}

// GetTunnelEgressBytesOk returns a tuple with the TunnelEgressBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelEgressBytesOk() (*float64, bool) {
	if o == nil || IsNil(o.TunnelEgressBytes) {
		return nil, false
	}
	return o.TunnelEgressBytes, true
}

// SetTunnelEgressBytes gets a reference to the given float64 and assigns it to the TunnelEgressBytes field.
func (o *AzureVirtualNetworkGatewayMetrics) SetTunnelEgressBytes(v float64) {
	o.TunnelEgressBytes = &v
}

// GetTunnelEgressPackets returns the TunnelEgressPackets field value if set, zero value otherwise.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelEgressPackets() float64 {
	if o == nil || IsNil(o.TunnelEgressPackets) {
		var ret float64
		return ret
	}
	return *o.TunnelEgressPackets
}

// GetTunnelEgressPacketsOk returns a tuple with the TunnelEgressPackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelEgressPacketsOk() (*float64, bool) {
	if o == nil || IsNil(o.TunnelEgressPackets) {
		return nil, false
	}
	return o.TunnelEgressPackets, true
}

// SetTunnelEgressPackets gets a reference to the given float64 and assigns it to the TunnelEgressPackets field.
func (o *AzureVirtualNetworkGatewayMetrics) SetTunnelEgressPackets(v float64) {
	o.TunnelEgressPackets = &v
}

// GetTunnelIngressPackets returns the TunnelIngressPackets field value if set, zero value otherwise.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelIngressPackets() float64 {
	if o == nil || IsNil(o.TunnelIngressPackets) {
		var ret float64
		return ret
	}
	return *o.TunnelIngressPackets
}

// GetTunnelIngressPacketsOk returns a tuple with the TunnelIngressPackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureVirtualNetworkGatewayMetrics) GetTunnelIngressPacketsOk() (*float64, bool) {
	if o == nil || IsNil(o.TunnelIngressPackets) {
		return nil, false
	}
	return o.TunnelIngressPackets, true
}

// SetTunnelIngressPackets gets a reference to the given float64 and assigns it to the TunnelIngressPackets field.
func (o *AzureVirtualNetworkGatewayMetrics) SetTunnelIngressPackets(v float64) {
	o.TunnelIngressPackets = &v
}

func (o AzureVirtualNetworkGatewayMetrics) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureVirtualNetworkGatewayMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AverageBandwidth) {
		toSerialize["averageBandwidth"] = o.AverageBandwidth
	}
	if !IsNil(o.TunnelAverageBandwidth) {
		toSerialize["tunnelAverageBandwidth"] = o.TunnelAverageBandwidth
	}
	if !IsNil(o.TunnelIngressBytes) {
		toSerialize["tunnelIngressBytes"] = o.TunnelIngressBytes
	}
	if !IsNil(o.TunnelEgressBytes) {
		toSerialize["tunnelEgressBytes"] = o.TunnelEgressBytes
	}
	if !IsNil(o.TunnelEgressPackets) {
		toSerialize["tunnelEgressPackets"] = o.TunnelEgressPackets
	}
	if !IsNil(o.TunnelIngressPackets) {
		toSerialize["tunnelIngressPackets"] = o.TunnelIngressPackets
	}
	return toSerialize, nil
}

type NullableAzureVirtualNetworkGatewayMetrics struct {
	value *AzureVirtualNetworkGatewayMetrics
	isSet bool
}

func (v NullableAzureVirtualNetworkGatewayMetrics) Get() *AzureVirtualNetworkGatewayMetrics {
	return v.value
}

func (v *NullableAzureVirtualNetworkGatewayMetrics) Set(val *AzureVirtualNetworkGatewayMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureVirtualNetworkGatewayMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureVirtualNetworkGatewayMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureVirtualNetworkGatewayMetrics(val *AzureVirtualNetworkGatewayMetrics) *NullableAzureVirtualNetworkGatewayMetrics {
	return &NullableAzureVirtualNetworkGatewayMetrics{value: val, isSet: true}
}

func (v NullableAzureVirtualNetworkGatewayMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureVirtualNetworkGatewayMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
