/*
Citrix Virtual App & Desktop Catalog Service 148.0.26750.34636

Catalog Service

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixquickdeploy

import (
	"encoding/json"
)

// checks if the Persona type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Persona{}

// Persona struct for Persona
type Persona struct {
	// The Id of the persona
	Id *string `json:"id,omitempty"`
	// Name of the persona
	Name *string `json:"name,omitempty"`
	// The VM SKU for the persona
	AzureVmSku *AzureVMSize `json:"azureVmSku,omitempty"`
	// Quantity of sessions supported per-machine.
	SessionSupport *SessionSupport `json:"sessionSupport,omitempty"`
	// Number of sessions per vm. Value is 1 for Single Session Personas
	SessionsPerVm *int32 `json:"sessionsPerVm,omitempty"`
	// The GPU memory in MB
	GpuMemoryInMB *int32 `json:"gpuMemoryInMB,omitempty"`
	// The cost per user per month for the persona
	EstimatedCredits *int32 `json:"estimatedCredits,omitempty"`
}

// NewPersonaWithDefaults instantiates a new Persona object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonaWithDefaults() *Persona {
	this := Persona{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Persona) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Persona) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Persona) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Persona) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Persona) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Persona) SetName(v string) {
	o.Name = &v
}

// GetAzureVmSku returns the AzureVmSku field value if set, zero value otherwise.
func (o *Persona) GetAzureVmSku() AzureVMSize {
	if o == nil || IsNil(o.AzureVmSku) {
		var ret AzureVMSize
		return ret
	}
	return *o.AzureVmSku
}

// GetAzureVmSkuOk returns a tuple with the AzureVmSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Persona) GetAzureVmSkuOk() (*AzureVMSize, bool) {
	if o == nil || IsNil(o.AzureVmSku) {
		return nil, false
	}
	return o.AzureVmSku, true
}

// SetAzureVmSku gets a reference to the given AzureVMSize and assigns it to the AzureVmSku field.
func (o *Persona) SetAzureVmSku(v AzureVMSize) {
	o.AzureVmSku = &v
}

// GetSessionSupport returns the SessionSupport field value if set, zero value otherwise.
func (o *Persona) GetSessionSupport() SessionSupport {
	if o == nil || IsNil(o.SessionSupport) {
		var ret SessionSupport
		return ret
	}
	return *o.SessionSupport
}

// GetSessionSupportOk returns a tuple with the SessionSupport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Persona) GetSessionSupportOk() (*SessionSupport, bool) {
	if o == nil || IsNil(o.SessionSupport) {
		return nil, false
	}
	return o.SessionSupport, true
}

// SetSessionSupport gets a reference to the given SessionSupport and assigns it to the SessionSupport field.
func (o *Persona) SetSessionSupport(v SessionSupport) {
	o.SessionSupport = &v
}

// GetSessionsPerVm returns the SessionsPerVm field value if set, zero value otherwise.
func (o *Persona) GetSessionsPerVm() int32 {
	if o == nil || IsNil(o.SessionsPerVm) {
		var ret int32
		return ret
	}
	return *o.SessionsPerVm
}

// GetSessionsPerVmOk returns a tuple with the SessionsPerVm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Persona) GetSessionsPerVmOk() (*int32, bool) {
	if o == nil || IsNil(o.SessionsPerVm) {
		return nil, false
	}
	return o.SessionsPerVm, true
}

// SetSessionsPerVm gets a reference to the given int32 and assigns it to the SessionsPerVm field.
func (o *Persona) SetSessionsPerVm(v int32) {
	o.SessionsPerVm = &v
}

// GetGpuMemoryInMB returns the GpuMemoryInMB field value if set, zero value otherwise.
func (o *Persona) GetGpuMemoryInMB() int32 {
	if o == nil || IsNil(o.GpuMemoryInMB) {
		var ret int32
		return ret
	}
	return *o.GpuMemoryInMB
}

// GetGpuMemoryInMBOk returns a tuple with the GpuMemoryInMB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Persona) GetGpuMemoryInMBOk() (*int32, bool) {
	if o == nil || IsNil(o.GpuMemoryInMB) {
		return nil, false
	}
	return o.GpuMemoryInMB, true
}

// SetGpuMemoryInMB gets a reference to the given int32 and assigns it to the GpuMemoryInMB field.
func (o *Persona) SetGpuMemoryInMB(v int32) {
	o.GpuMemoryInMB = &v
}

// GetEstimatedCredits returns the EstimatedCredits field value if set, zero value otherwise.
func (o *Persona) GetEstimatedCredits() int32 {
	if o == nil || IsNil(o.EstimatedCredits) {
		var ret int32
		return ret
	}
	return *o.EstimatedCredits
}

// GetEstimatedCreditsOk returns a tuple with the EstimatedCredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Persona) GetEstimatedCreditsOk() (*int32, bool) {
	if o == nil || IsNil(o.EstimatedCredits) {
		return nil, false
	}
	return o.EstimatedCredits, true
}

// SetEstimatedCredits gets a reference to the given int32 and assigns it to the EstimatedCredits field.
func (o *Persona) SetEstimatedCredits(v int32) {
	o.EstimatedCredits = &v
}

func (o Persona) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Persona) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AzureVmSku) {
		toSerialize["azureVmSku"] = o.AzureVmSku
	}
	if !IsNil(o.SessionSupport) {
		toSerialize["sessionSupport"] = o.SessionSupport
	}
	if !IsNil(o.SessionsPerVm) {
		toSerialize["sessionsPerVm"] = o.SessionsPerVm
	}
	if !IsNil(o.GpuMemoryInMB) {
		toSerialize["gpuMemoryInMB"] = o.GpuMemoryInMB
	}
	if !IsNil(o.EstimatedCredits) {
		toSerialize["estimatedCredits"] = o.EstimatedCredits
	}
	return toSerialize, nil
}

type NullablePersona struct {
	value *Persona
	isSet bool
}

func (v NullablePersona) Get() *Persona {
	return v.value
}

func (v *NullablePersona) Set(val *Persona) {
	v.value = val
	v.isSet = true
}

func (v NullablePersona) IsSet() bool {
	return v.isSet
}

func (v *NullablePersona) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersona(val *Persona) *NullablePersona {
	return &NullablePersona{value: val, isSet: true}
}

func (v NullablePersona) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersona) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
