/*
Citrix Virtual Apps and Desktops REST API TECHPREVIEW

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: techpreview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the VDAComponentParameterModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VDAComponentParameterModel{}

// VDAComponentParameterModel Model of VDA component's parameter.
type VDAComponentParameterModel struct {
	// Name of this parameter object.
	ParameterName *string `json:"ParameterName,omitempty"`
	// Id of this parameter object.
	ParameterId *string `json:"ParameterId,omitempty"`
	// Description of this parameter object.
	ParameterDescription *string `json:"ParameterDescription,omitempty"`
	// Type of this parameter object.
	ParameterType *string `json:"ParameterType,omitempty"`
}

// NewVDAComponentParameterModel instantiates a new VDAComponentParameterModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVDAComponentParameterModel() *VDAComponentParameterModel {
	this := VDAComponentParameterModel{}
	return &this
}

// NewVDAComponentParameterModelWithDefaults instantiates a new VDAComponentParameterModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVDAComponentParameterModelWithDefaults() *VDAComponentParameterModel {
	this := VDAComponentParameterModel{}
	return &this
}

// GetParameterName returns the ParameterName field value if set, zero value otherwise.
func (o *VDAComponentParameterModel) GetParameterName() string {
	if o == nil || IsNil(o.ParameterName) {
		var ret string
		return ret
	}
	return *o.ParameterName
}

// GetParameterNameOk returns a tuple with the ParameterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VDAComponentParameterModel) GetParameterNameOk() (*string, bool) {
	if o == nil || IsNil(o.ParameterName) {
		return nil, false
	}
	return o.ParameterName, true
}

// HasParameterName returns a boolean if a field has been set.
func (o *VDAComponentParameterModel) HasParameterName() bool {
	if o != nil && !IsNil(o.ParameterName) {
		return true
	}

	return false
}

// SetParameterName gets a reference to the given string and assigns it to the ParameterName field.
func (o *VDAComponentParameterModel) SetParameterName(v string) {
	o.ParameterName = &v
}

// GetParameterId returns the ParameterId field value if set, zero value otherwise.
func (o *VDAComponentParameterModel) GetParameterId() string {
	if o == nil || IsNil(o.ParameterId) {
		var ret string
		return ret
	}
	return *o.ParameterId
}

// GetParameterIdOk returns a tuple with the ParameterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VDAComponentParameterModel) GetParameterIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParameterId) {
		return nil, false
	}
	return o.ParameterId, true
}

// HasParameterId returns a boolean if a field has been set.
func (o *VDAComponentParameterModel) HasParameterId() bool {
	if o != nil && !IsNil(o.ParameterId) {
		return true
	}

	return false
}

// SetParameterId gets a reference to the given string and assigns it to the ParameterId field.
func (o *VDAComponentParameterModel) SetParameterId(v string) {
	o.ParameterId = &v
}

// GetParameterDescription returns the ParameterDescription field value if set, zero value otherwise.
func (o *VDAComponentParameterModel) GetParameterDescription() string {
	if o == nil || IsNil(o.ParameterDescription) {
		var ret string
		return ret
	}
	return *o.ParameterDescription
}

// GetParameterDescriptionOk returns a tuple with the ParameterDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VDAComponentParameterModel) GetParameterDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ParameterDescription) {
		return nil, false
	}
	return o.ParameterDescription, true
}

// HasParameterDescription returns a boolean if a field has been set.
func (o *VDAComponentParameterModel) HasParameterDescription() bool {
	if o != nil && !IsNil(o.ParameterDescription) {
		return true
	}

	return false
}

// SetParameterDescription gets a reference to the given string and assigns it to the ParameterDescription field.
func (o *VDAComponentParameterModel) SetParameterDescription(v string) {
	o.ParameterDescription = &v
}

// GetParameterType returns the ParameterType field value if set, zero value otherwise.
func (o *VDAComponentParameterModel) GetParameterType() string {
	if o == nil || IsNil(o.ParameterType) {
		var ret string
		return ret
	}
	return *o.ParameterType
}

// GetParameterTypeOk returns a tuple with the ParameterType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VDAComponentParameterModel) GetParameterTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ParameterType) {
		return nil, false
	}
	return o.ParameterType, true
}

// HasParameterType returns a boolean if a field has been set.
func (o *VDAComponentParameterModel) HasParameterType() bool {
	if o != nil && !IsNil(o.ParameterType) {
		return true
	}

	return false
}

// SetParameterType gets a reference to the given string and assigns it to the ParameterType field.
func (o *VDAComponentParameterModel) SetParameterType(v string) {
	o.ParameterType = &v
}

func (o VDAComponentParameterModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VDAComponentParameterModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ParameterName) {
		toSerialize["ParameterName"] = o.ParameterName
	}
	if !IsNil(o.ParameterId) {
		toSerialize["ParameterId"] = o.ParameterId
	}
	if !IsNil(o.ParameterDescription) {
		toSerialize["ParameterDescription"] = o.ParameterDescription
	}
	if !IsNil(o.ParameterType) {
		toSerialize["ParameterType"] = o.ParameterType
	}
	return toSerialize, nil
}

type NullableVDAComponentParameterModel struct {
	value *VDAComponentParameterModel
	isSet bool
}

func (v NullableVDAComponentParameterModel) Get() *VDAComponentParameterModel {
	return v.value
}

func (v *NullableVDAComponentParameterModel) Set(val *VDAComponentParameterModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVDAComponentParameterModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVDAComponentParameterModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVDAComponentParameterModel(val *VDAComponentParameterModel) *NullableVDAComponentParameterModel {
	return &NullableVDAComponentParameterModel{value: val, isSet: true}
}

func (v NullableVDAComponentParameterModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVDAComponentParameterModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


