/*
Citrix Virtual Apps and Desktops Rest API for Developer Portal

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: devportal-ga
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the ZonedItemsRequestModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZonedItemsRequestModel{}

// ZonedItemsRequestModel Request model for zoned items.
type ZonedItemsRequestModel struct {
	Items []ZonedItemRequestModel `json:"Items,omitempty"`
}

// NewZonedItemsRequestModel instantiates a new ZonedItemsRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZonedItemsRequestModel() *ZonedItemsRequestModel {
	this := ZonedItemsRequestModel{}
	return &this
}

// NewZonedItemsRequestModelWithDefaults instantiates a new ZonedItemsRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZonedItemsRequestModelWithDefaults() *ZonedItemsRequestModel {
	this := ZonedItemsRequestModel{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ZonedItemsRequestModel) GetItems() []ZonedItemRequestModel {
	if o == nil {
		var ret []ZonedItemRequestModel
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ZonedItemsRequestModel) GetItemsOk() ([]ZonedItemRequestModel, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ZonedItemsRequestModel) HasItems() bool {
	if o != nil && IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ZonedItemRequestModel and assigns it to the Items field.
func (o *ZonedItemsRequestModel) SetItems(v []ZonedItemRequestModel) {
	o.Items = v
}

func (o ZonedItemsRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZonedItemsRequestModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["Items"] = o.Items
	}
	return toSerialize, nil
}

type NullableZonedItemsRequestModel struct {
	value *ZonedItemsRequestModel
	isSet bool
}

func (v NullableZonedItemsRequestModel) Get() *ZonedItemsRequestModel {
	return v.value
}

func (v *NullableZonedItemsRequestModel) Set(val *ZonedItemsRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableZonedItemsRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableZonedItemsRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZonedItemsRequestModel(val *ZonedItemsRequestModel) *NullableZonedItemsRequestModel {
	return &NullableZonedItemsRequestModel{value: val, isSet: true}
}

func (v NullableZonedItemsRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZonedItemsRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


