/*
Citrix Virtual Apps and Desktops REST API TECHPREVIEW

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: techpreview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the HypervisorVmValidationResponseModelHypervisorVmResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HypervisorVmValidationResponseModelHypervisorVmResource{}

// HypervisorVmValidationResponseModelHypervisorVmResource Virtual machine info.
type HypervisorVmValidationResponseModelHypervisorVmResource struct {
	// Id of the resource.
	Id *string `json:"Id,omitempty"`
	// Name of the resource.
	Name *string `json:"Name,omitempty"`
	// XenApp & XenDesktop path to the resource on the hypervisor.  An example value is: `XDHyp:\\Connections\\{{hypervisor name}}\\{{vm name}}.vm\\{{snapshot name}}.snapshot` or `XDHyp:\\HostingUnits\\{{resource pool name}}\\{{resource name}}.{{resource type}}`
	XDPath *string `json:"XDPath,omitempty"`
	// Path to the object, relative to the resource pool from which it was queried. `{{vm name}}.vm/{{snapshot name}}.snapshot`
	RelativePath *string `json:"RelativePath,omitempty"`
	// Full path to the resource, including the hypervisor, relative to the root of the API. Example: `Hypervisors/{{hypervisor id}}/ResourcePools/{{resource pool id}}/Resources/{{RelativePath}}`
	FullRelativePath *string `json:"FullRelativePath,omitempty"`
	// Type of resource.
	ResourceType string `json:"ResourceType"`
	// The type name of the hypervisor resource object.
	ObjectTypeName *string `json:"ObjectTypeName,omitempty"`
	ResourceContainer *HypervisorResourceRefResponseModelAllOfResourceContainer `json:"ResourceContainer,omitempty"`
	// Citrix Apps and Desktops path to the resource on the ResourcePool.  An example value is: `XDHyp:\\HostingUnits\\{{resource pool name}}\\{{resource name}}.{{resource type}}` This value 
	ResourcePoolXDPath *string `json:"ResourcePoolXDPath,omitempty"`
	// Name of the resource, with the type concatenated. i.e. \"name.type\".
	FullName string `json:"FullName"`
	// Indicates whether the resource is a container.
	IsContainer bool `json:"IsContainer"`
	// Child resources, when the resource is a container.
	Children []HypervisorResourceResponseModel `json:"Children,omitempty"`
	// Indicates whether the resource is a machine.
	IsMachine bool `json:"IsMachine"`
	// Indicates whether the resource can have a snapshot taken.
	IsSnapshotable bool `json:"IsSnapshotable"`
	// Path to the resource, relative to the special \"AllResources\" resource pool associated with the hypervisor.
	AllResourcesRelativePath string `json:"AllResourcesRelativePath"`
	ResourcePool HypervisorResourceResponseModelAllOfResourcePool `json:"ResourcePool"`
	// Indicates whether the object is a valid symbolic link.
	IsSymLink bool `json:"IsSymLink"`
	// Additional data about the object in the form of key-value pairs.
	AdditionalData []NameValueStringPairModel `json:"AdditionalData,omitempty"`
	// Number of CPUs, if known.
	CpuCount *int32 `json:"CpuCount,omitempty"`
	// Memory in megabytes, if known.
	MemoryMB *int32 `json:"MemoryMB,omitempty"`
	// Hard disk size in gigabytes, if known.
	HardDiskSizeGB *int32 `json:"HardDiskSizeGB,omitempty"`
	// Minimum memory required to run this VM or snapshot, in megabytes, if known.
	MinMemoryMB *int32 `json:"MinMemoryMB,omitempty"`
	// Network mappings associated with the VM, if known.
	NetworkMappings []NetworkMapResponseModel `json:"NetworkMappings,omitempty"`
	// Disks attached to the VM, if known.
	AttachedDisks []AttachedDiskResponseModel `json:"AttachedDisks,omitempty"`
	// Id of the VM, as defined by the hypervisor.
	VMId string `json:"VMId"`
	// MAC address of the VM.
	MacAddress *string `json:"MacAddress,omitempty"`
}

// NewHypervisorVmValidationResponseModelHypervisorVmResource instantiates a new HypervisorVmValidationResponseModelHypervisorVmResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHypervisorVmValidationResponseModelHypervisorVmResource(resourceType string, fullName string, isContainer bool, isMachine bool, isSnapshotable bool, allResourcesRelativePath string, resourcePool HypervisorResourceResponseModelAllOfResourcePool, isSymLink bool, vMId string) *HypervisorVmValidationResponseModelHypervisorVmResource {
	this := HypervisorVmValidationResponseModelHypervisorVmResource{}
	this.ResourceType = resourceType
	this.FullName = fullName
	this.IsContainer = isContainer
	this.IsMachine = isMachine
	this.IsSnapshotable = isSnapshotable
	this.AllResourcesRelativePath = allResourcesRelativePath
	this.ResourcePool = resourcePool
	this.IsSymLink = isSymLink
	this.VMId = vMId
	return &this
}

// NewHypervisorVmValidationResponseModelHypervisorVmResourceWithDefaults instantiates a new HypervisorVmValidationResponseModelHypervisorVmResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHypervisorVmValidationResponseModelHypervisorVmResourceWithDefaults() *HypervisorVmValidationResponseModelHypervisorVmResource {
	this := HypervisorVmValidationResponseModelHypervisorVmResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetName(v string) {
	o.Name = &v
}

// GetXDPath returns the XDPath field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetXDPath() string {
	if o == nil || IsNil(o.XDPath) {
		var ret string
		return ret
	}
	return *o.XDPath
}

// GetXDPathOk returns a tuple with the XDPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetXDPathOk() (*string, bool) {
	if o == nil || IsNil(o.XDPath) {
		return nil, false
	}
	return o.XDPath, true
}

// HasXDPath returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasXDPath() bool {
	if o != nil && !IsNil(o.XDPath) {
		return true
	}

	return false
}

// SetXDPath gets a reference to the given string and assigns it to the XDPath field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetXDPath(v string) {
	o.XDPath = &v
}

// GetRelativePath returns the RelativePath field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetRelativePath() string {
	if o == nil || IsNil(o.RelativePath) {
		var ret string
		return ret
	}
	return *o.RelativePath
}

// GetRelativePathOk returns a tuple with the RelativePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetRelativePathOk() (*string, bool) {
	if o == nil || IsNil(o.RelativePath) {
		return nil, false
	}
	return o.RelativePath, true
}

// HasRelativePath returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasRelativePath() bool {
	if o != nil && !IsNil(o.RelativePath) {
		return true
	}

	return false
}

// SetRelativePath gets a reference to the given string and assigns it to the RelativePath field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetRelativePath(v string) {
	o.RelativePath = &v
}

// GetFullRelativePath returns the FullRelativePath field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetFullRelativePath() string {
	if o == nil || IsNil(o.FullRelativePath) {
		var ret string
		return ret
	}
	return *o.FullRelativePath
}

// GetFullRelativePathOk returns a tuple with the FullRelativePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetFullRelativePathOk() (*string, bool) {
	if o == nil || IsNil(o.FullRelativePath) {
		return nil, false
	}
	return o.FullRelativePath, true
}

// HasFullRelativePath returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasFullRelativePath() bool {
	if o != nil && !IsNil(o.FullRelativePath) {
		return true
	}

	return false
}

// SetFullRelativePath gets a reference to the given string and assigns it to the FullRelativePath field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetFullRelativePath(v string) {
	o.FullRelativePath = &v
}

// GetResourceType returns the ResourceType field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetResourceType(v string) {
	o.ResourceType = v
}

// GetObjectTypeName returns the ObjectTypeName field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetObjectTypeName() string {
	if o == nil || IsNil(o.ObjectTypeName) {
		var ret string
		return ret
	}
	return *o.ObjectTypeName
}

// GetObjectTypeNameOk returns a tuple with the ObjectTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetObjectTypeNameOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectTypeName) {
		return nil, false
	}
	return o.ObjectTypeName, true
}

// HasObjectTypeName returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasObjectTypeName() bool {
	if o != nil && !IsNil(o.ObjectTypeName) {
		return true
	}

	return false
}

// SetObjectTypeName gets a reference to the given string and assigns it to the ObjectTypeName field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetObjectTypeName(v string) {
	o.ObjectTypeName = &v
}

// GetResourceContainer returns the ResourceContainer field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetResourceContainer() HypervisorResourceRefResponseModelAllOfResourceContainer {
	if o == nil || IsNil(o.ResourceContainer) {
		var ret HypervisorResourceRefResponseModelAllOfResourceContainer
		return ret
	}
	return *o.ResourceContainer
}

// GetResourceContainerOk returns a tuple with the ResourceContainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetResourceContainerOk() (*HypervisorResourceRefResponseModelAllOfResourceContainer, bool) {
	if o == nil || IsNil(o.ResourceContainer) {
		return nil, false
	}
	return o.ResourceContainer, true
}

// HasResourceContainer returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasResourceContainer() bool {
	if o != nil && !IsNil(o.ResourceContainer) {
		return true
	}

	return false
}

// SetResourceContainer gets a reference to the given HypervisorResourceRefResponseModelAllOfResourceContainer and assigns it to the ResourceContainer field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetResourceContainer(v HypervisorResourceRefResponseModelAllOfResourceContainer) {
	o.ResourceContainer = &v
}

// GetResourcePoolXDPath returns the ResourcePoolXDPath field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetResourcePoolXDPath() string {
	if o == nil || IsNil(o.ResourcePoolXDPath) {
		var ret string
		return ret
	}
	return *o.ResourcePoolXDPath
}

// GetResourcePoolXDPathOk returns a tuple with the ResourcePoolXDPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetResourcePoolXDPathOk() (*string, bool) {
	if o == nil || IsNil(o.ResourcePoolXDPath) {
		return nil, false
	}
	return o.ResourcePoolXDPath, true
}

// HasResourcePoolXDPath returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasResourcePoolXDPath() bool {
	if o != nil && !IsNil(o.ResourcePoolXDPath) {
		return true
	}

	return false
}

// SetResourcePoolXDPath gets a reference to the given string and assigns it to the ResourcePoolXDPath field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetResourcePoolXDPath(v string) {
	o.ResourcePoolXDPath = &v
}

// GetFullName returns the FullName field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetFullName(v string) {
	o.FullName = v
}

// GetIsContainer returns the IsContainer field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIsContainer() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsContainer
}

// GetIsContainerOk returns a tuple with the IsContainer field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIsContainerOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsContainer, true
}

// SetIsContainer sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetIsContainer(v bool) {
	o.IsContainer = v
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetChildren() []HypervisorResourceResponseModel {
	if o == nil || IsNil(o.Children) {
		var ret []HypervisorResourceResponseModel
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetChildrenOk() ([]HypervisorResourceResponseModel, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []HypervisorResourceResponseModel and assigns it to the Children field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetChildren(v []HypervisorResourceResponseModel) {
	o.Children = v
}

// GetIsMachine returns the IsMachine field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIsMachine() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMachine
}

// GetIsMachineOk returns a tuple with the IsMachine field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIsMachineOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMachine, true
}

// SetIsMachine sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetIsMachine(v bool) {
	o.IsMachine = v
}

// GetIsSnapshotable returns the IsSnapshotable field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIsSnapshotable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSnapshotable
}

// GetIsSnapshotableOk returns a tuple with the IsSnapshotable field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIsSnapshotableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsSnapshotable, true
}

// SetIsSnapshotable sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetIsSnapshotable(v bool) {
	o.IsSnapshotable = v
}

// GetAllResourcesRelativePath returns the AllResourcesRelativePath field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetAllResourcesRelativePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AllResourcesRelativePath
}

// GetAllResourcesRelativePathOk returns a tuple with the AllResourcesRelativePath field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetAllResourcesRelativePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllResourcesRelativePath, true
}

// SetAllResourcesRelativePath sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetAllResourcesRelativePath(v string) {
	o.AllResourcesRelativePath = v
}

// GetResourcePool returns the ResourcePool field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetResourcePool() HypervisorResourceResponseModelAllOfResourcePool {
	if o == nil {
		var ret HypervisorResourceResponseModelAllOfResourcePool
		return ret
	}

	return o.ResourcePool
}

// GetResourcePoolOk returns a tuple with the ResourcePool field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetResourcePoolOk() (*HypervisorResourceResponseModelAllOfResourcePool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourcePool, true
}

// SetResourcePool sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetResourcePool(v HypervisorResourceResponseModelAllOfResourcePool) {
	o.ResourcePool = v
}

// GetIsSymLink returns the IsSymLink field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIsSymLink() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSymLink
}

// GetIsSymLinkOk returns a tuple with the IsSymLink field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetIsSymLinkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsSymLink, true
}

// SetIsSymLink sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetIsSymLink(v bool) {
	o.IsSymLink = v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetAdditionalData() []NameValueStringPairModel {
	if o == nil || IsNil(o.AdditionalData) {
		var ret []NameValueStringPairModel
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetAdditionalDataOk() ([]NameValueStringPairModel, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given []NameValueStringPairModel and assigns it to the AdditionalData field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetAdditionalData(v []NameValueStringPairModel) {
	o.AdditionalData = v
}

// GetCpuCount returns the CpuCount field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetCpuCount() int32 {
	if o == nil || IsNil(o.CpuCount) {
		var ret int32
		return ret
	}
	return *o.CpuCount
}

// GetCpuCountOk returns a tuple with the CpuCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetCpuCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuCount) {
		return nil, false
	}
	return o.CpuCount, true
}

// HasCpuCount returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasCpuCount() bool {
	if o != nil && !IsNil(o.CpuCount) {
		return true
	}

	return false
}

// SetCpuCount gets a reference to the given int32 and assigns it to the CpuCount field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetCpuCount(v int32) {
	o.CpuCount = &v
}

// GetMemoryMB returns the MemoryMB field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetMemoryMB() int32 {
	if o == nil || IsNil(o.MemoryMB) {
		var ret int32
		return ret
	}
	return *o.MemoryMB
}

// GetMemoryMBOk returns a tuple with the MemoryMB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetMemoryMBOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryMB) {
		return nil, false
	}
	return o.MemoryMB, true
}

// HasMemoryMB returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasMemoryMB() bool {
	if o != nil && !IsNil(o.MemoryMB) {
		return true
	}

	return false
}

// SetMemoryMB gets a reference to the given int32 and assigns it to the MemoryMB field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetMemoryMB(v int32) {
	o.MemoryMB = &v
}

// GetHardDiskSizeGB returns the HardDiskSizeGB field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetHardDiskSizeGB() int32 {
	if o == nil || IsNil(o.HardDiskSizeGB) {
		var ret int32
		return ret
	}
	return *o.HardDiskSizeGB
}

// GetHardDiskSizeGBOk returns a tuple with the HardDiskSizeGB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetHardDiskSizeGBOk() (*int32, bool) {
	if o == nil || IsNil(o.HardDiskSizeGB) {
		return nil, false
	}
	return o.HardDiskSizeGB, true
}

// HasHardDiskSizeGB returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasHardDiskSizeGB() bool {
	if o != nil && !IsNil(o.HardDiskSizeGB) {
		return true
	}

	return false
}

// SetHardDiskSizeGB gets a reference to the given int32 and assigns it to the HardDiskSizeGB field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetHardDiskSizeGB(v int32) {
	o.HardDiskSizeGB = &v
}

// GetMinMemoryMB returns the MinMemoryMB field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetMinMemoryMB() int32 {
	if o == nil || IsNil(o.MinMemoryMB) {
		var ret int32
		return ret
	}
	return *o.MinMemoryMB
}

// GetMinMemoryMBOk returns a tuple with the MinMemoryMB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetMinMemoryMBOk() (*int32, bool) {
	if o == nil || IsNil(o.MinMemoryMB) {
		return nil, false
	}
	return o.MinMemoryMB, true
}

// HasMinMemoryMB returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasMinMemoryMB() bool {
	if o != nil && !IsNil(o.MinMemoryMB) {
		return true
	}

	return false
}

// SetMinMemoryMB gets a reference to the given int32 and assigns it to the MinMemoryMB field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetMinMemoryMB(v int32) {
	o.MinMemoryMB = &v
}

// GetNetworkMappings returns the NetworkMappings field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetNetworkMappings() []NetworkMapResponseModel {
	if o == nil || IsNil(o.NetworkMappings) {
		var ret []NetworkMapResponseModel
		return ret
	}
	return o.NetworkMappings
}

// GetNetworkMappingsOk returns a tuple with the NetworkMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetNetworkMappingsOk() ([]NetworkMapResponseModel, bool) {
	if o == nil || IsNil(o.NetworkMappings) {
		return nil, false
	}
	return o.NetworkMappings, true
}

// HasNetworkMappings returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasNetworkMappings() bool {
	if o != nil && !IsNil(o.NetworkMappings) {
		return true
	}

	return false
}

// SetNetworkMappings gets a reference to the given []NetworkMapResponseModel and assigns it to the NetworkMappings field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetNetworkMappings(v []NetworkMapResponseModel) {
	o.NetworkMappings = v
}

// GetAttachedDisks returns the AttachedDisks field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetAttachedDisks() []AttachedDiskResponseModel {
	if o == nil || IsNil(o.AttachedDisks) {
		var ret []AttachedDiskResponseModel
		return ret
	}
	return o.AttachedDisks
}

// GetAttachedDisksOk returns a tuple with the AttachedDisks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetAttachedDisksOk() ([]AttachedDiskResponseModel, bool) {
	if o == nil || IsNil(o.AttachedDisks) {
		return nil, false
	}
	return o.AttachedDisks, true
}

// HasAttachedDisks returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasAttachedDisks() bool {
	if o != nil && !IsNil(o.AttachedDisks) {
		return true
	}

	return false
}

// SetAttachedDisks gets a reference to the given []AttachedDiskResponseModel and assigns it to the AttachedDisks field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetAttachedDisks(v []AttachedDiskResponseModel) {
	o.AttachedDisks = v
}

// GetVMId returns the VMId field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetVMId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VMId
}

// GetVMIdOk returns a tuple with the VMId field value
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetVMIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VMId, true
}

// SetVMId sets field value
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetVMId(v string) {
	o.VMId = v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress) {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) GetMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) HasMacAddress() bool {
	if o != nil && !IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *HypervisorVmValidationResponseModelHypervisorVmResource) SetMacAddress(v string) {
	o.MacAddress = &v
}

func (o HypervisorVmValidationResponseModelHypervisorVmResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HypervisorVmValidationResponseModelHypervisorVmResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["Id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.XDPath) {
		toSerialize["XDPath"] = o.XDPath
	}
	if !IsNil(o.RelativePath) {
		toSerialize["RelativePath"] = o.RelativePath
	}
	if !IsNil(o.FullRelativePath) {
		toSerialize["FullRelativePath"] = o.FullRelativePath
	}
	toSerialize["ResourceType"] = o.ResourceType
	if !IsNil(o.ObjectTypeName) {
		toSerialize["ObjectTypeName"] = o.ObjectTypeName
	}
	if !IsNil(o.ResourceContainer) {
		toSerialize["ResourceContainer"] = o.ResourceContainer
	}
	if !IsNil(o.ResourcePoolXDPath) {
		toSerialize["ResourcePoolXDPath"] = o.ResourcePoolXDPath
	}
	toSerialize["FullName"] = o.FullName
	toSerialize["IsContainer"] = o.IsContainer
	if !IsNil(o.Children) {
		toSerialize["Children"] = o.Children
	}
	toSerialize["IsMachine"] = o.IsMachine
	toSerialize["IsSnapshotable"] = o.IsSnapshotable
	toSerialize["AllResourcesRelativePath"] = o.AllResourcesRelativePath
	toSerialize["ResourcePool"] = o.ResourcePool
	toSerialize["IsSymLink"] = o.IsSymLink
	if !IsNil(o.AdditionalData) {
		toSerialize["AdditionalData"] = o.AdditionalData
	}
	if !IsNil(o.CpuCount) {
		toSerialize["CpuCount"] = o.CpuCount
	}
	if !IsNil(o.MemoryMB) {
		toSerialize["MemoryMB"] = o.MemoryMB
	}
	if !IsNil(o.HardDiskSizeGB) {
		toSerialize["HardDiskSizeGB"] = o.HardDiskSizeGB
	}
	if !IsNil(o.MinMemoryMB) {
		toSerialize["MinMemoryMB"] = o.MinMemoryMB
	}
	if !IsNil(o.NetworkMappings) {
		toSerialize["NetworkMappings"] = o.NetworkMappings
	}
	if !IsNil(o.AttachedDisks) {
		toSerialize["AttachedDisks"] = o.AttachedDisks
	}
	toSerialize["VMId"] = o.VMId
	if !IsNil(o.MacAddress) {
		toSerialize["MacAddress"] = o.MacAddress
	}
	return toSerialize, nil
}

type NullableHypervisorVmValidationResponseModelHypervisorVmResource struct {
	value *HypervisorVmValidationResponseModelHypervisorVmResource
	isSet bool
}

func (v NullableHypervisorVmValidationResponseModelHypervisorVmResource) Get() *HypervisorVmValidationResponseModelHypervisorVmResource {
	return v.value
}

func (v *NullableHypervisorVmValidationResponseModelHypervisorVmResource) Set(val *HypervisorVmValidationResponseModelHypervisorVmResource) {
	v.value = val
	v.isSet = true
}

func (v NullableHypervisorVmValidationResponseModelHypervisorVmResource) IsSet() bool {
	return v.isSet
}

func (v *NullableHypervisorVmValidationResponseModelHypervisorVmResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHypervisorVmValidationResponseModelHypervisorVmResource(val *HypervisorVmValidationResponseModelHypervisorVmResource) *NullableHypervisorVmValidationResponseModelHypervisorVmResource {
	return &NullableHypervisorVmValidationResponseModelHypervisorVmResource{value: val, isSet: true}
}

func (v NullableHypervisorVmValidationResponseModelHypervisorVmResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHypervisorVmValidationResponseModelHypervisorVmResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


