/*
Citrix Virtual Apps and Desktops Rest API for Developer Portal

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: devportal-onprem-ga
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the ProvisionedVirtualMachineConfigurationResultantSetResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisionedVirtualMachineConfigurationResultantSetResponseModel{}

// ProvisionedVirtualMachineConfigurationResultantSetResponseModel The resultant configuration properties for virtual machines created using Machine Creation Services. This merges properties at the provisioning scheme level with those set on a machine with Set-ProvVM specifically.
type ProvisionedVirtualMachineConfigurationResultantSetResponseModel struct {
	// The number of processors that VMs will be created with when using this configuration.
	CpuCount NullableInt32 `json:"CpuCount,omitempty"`
	// The maximum amount of memory that VMs will be created with when using this configuration.
	MemoryMB NullableInt32 `json:"MemoryMB,omitempty"`
	MachineProfile *HypervisorResourceRefResponseModel `json:"MachineProfile,omitempty"`
	// Service offering used by Cloud provisioned VMs.
	ServiceOffering NullableString `json:"ServiceOffering,omitempty"`
	// The properties of the provisioning scheme that are specific to the target hosting infrastructure.
	CustomProperties []NameValueStringPairModel `json:"CustomProperties,omitempty"`
	// provisioning scheme name
	ProvisioningSchemeName NullableString `json:"ProvisioningSchemeName,omitempty"`
	// provisioning scheme uid
	ProvisioningSchemeId *string `json:"ProvisioningSchemeId,omitempty"`
	// VM Id
	VMId NullableString `json:"VMId,omitempty"`
	// VM Name
	VMName NullableString `json:"VMName,omitempty"`
}

// NewProvisionedVirtualMachineConfigurationResultantSetResponseModel instantiates a new ProvisionedVirtualMachineConfigurationResultantSetResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisionedVirtualMachineConfigurationResultantSetResponseModel() *ProvisionedVirtualMachineConfigurationResultantSetResponseModel {
	this := ProvisionedVirtualMachineConfigurationResultantSetResponseModel{}
	return &this
}

// NewProvisionedVirtualMachineConfigurationResultantSetResponseModelWithDefaults instantiates a new ProvisionedVirtualMachineConfigurationResultantSetResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisionedVirtualMachineConfigurationResultantSetResponseModelWithDefaults() *ProvisionedVirtualMachineConfigurationResultantSetResponseModel {
	this := ProvisionedVirtualMachineConfigurationResultantSetResponseModel{}
	return &this
}

// GetCpuCount returns the CpuCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetCpuCount() int32 {
	if o == nil || IsNil(o.CpuCount.Get()) {
		var ret int32
		return ret
	}
	return *o.CpuCount.Get()
}

// GetCpuCountOk returns a tuple with the CpuCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetCpuCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CpuCount.Get(), o.CpuCount.IsSet()
}

// HasCpuCount returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasCpuCount() bool {
	if o != nil && o.CpuCount.IsSet() {
		return true
	}

	return false
}

// SetCpuCount gets a reference to the given NullableInt32 and assigns it to the CpuCount field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetCpuCount(v int32) {
	o.CpuCount.Set(&v)
}
// SetCpuCountNil sets the value for CpuCount to be an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetCpuCountNil() {
	o.CpuCount.Set(nil)
}

// UnsetCpuCount ensures that no value is present for CpuCount, not even an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) UnsetCpuCount() {
	o.CpuCount.Unset()
}

// GetMemoryMB returns the MemoryMB field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetMemoryMB() int32 {
	if o == nil || IsNil(o.MemoryMB.Get()) {
		var ret int32
		return ret
	}
	return *o.MemoryMB.Get()
}

// GetMemoryMBOk returns a tuple with the MemoryMB field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetMemoryMBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MemoryMB.Get(), o.MemoryMB.IsSet()
}

// HasMemoryMB returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasMemoryMB() bool {
	if o != nil && o.MemoryMB.IsSet() {
		return true
	}

	return false
}

// SetMemoryMB gets a reference to the given NullableInt32 and assigns it to the MemoryMB field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetMemoryMB(v int32) {
	o.MemoryMB.Set(&v)
}
// SetMemoryMBNil sets the value for MemoryMB to be an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetMemoryMBNil() {
	o.MemoryMB.Set(nil)
}

// UnsetMemoryMB ensures that no value is present for MemoryMB, not even an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) UnsetMemoryMB() {
	o.MemoryMB.Unset()
}

// GetMachineProfile returns the MachineProfile field value if set, zero value otherwise.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetMachineProfile() HypervisorResourceRefResponseModel {
	if o == nil || IsNil(o.MachineProfile) {
		var ret HypervisorResourceRefResponseModel
		return ret
	}
	return *o.MachineProfile
}

// GetMachineProfileOk returns a tuple with the MachineProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetMachineProfileOk() (*HypervisorResourceRefResponseModel, bool) {
	if o == nil || IsNil(o.MachineProfile) {
		return nil, false
	}
	return o.MachineProfile, true
}

// HasMachineProfile returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasMachineProfile() bool {
	if o != nil && !IsNil(o.MachineProfile) {
		return true
	}

	return false
}

// SetMachineProfile gets a reference to the given HypervisorResourceRefResponseModel and assigns it to the MachineProfile field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetMachineProfile(v HypervisorResourceRefResponseModel) {
	o.MachineProfile = &v
}

// GetServiceOffering returns the ServiceOffering field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetServiceOffering() string {
	if o == nil || IsNil(o.ServiceOffering.Get()) {
		var ret string
		return ret
	}
	return *o.ServiceOffering.Get()
}

// GetServiceOfferingOk returns a tuple with the ServiceOffering field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetServiceOfferingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceOffering.Get(), o.ServiceOffering.IsSet()
}

// HasServiceOffering returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasServiceOffering() bool {
	if o != nil && o.ServiceOffering.IsSet() {
		return true
	}

	return false
}

// SetServiceOffering gets a reference to the given NullableString and assigns it to the ServiceOffering field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetServiceOffering(v string) {
	o.ServiceOffering.Set(&v)
}
// SetServiceOfferingNil sets the value for ServiceOffering to be an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetServiceOfferingNil() {
	o.ServiceOffering.Set(nil)
}

// UnsetServiceOffering ensures that no value is present for ServiceOffering, not even an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) UnsetServiceOffering() {
	o.ServiceOffering.Unset()
}

// GetCustomProperties returns the CustomProperties field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetCustomProperties() []NameValueStringPairModel {
	if o == nil {
		var ret []NameValueStringPairModel
		return ret
	}
	return o.CustomProperties
}

// GetCustomPropertiesOk returns a tuple with the CustomProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetCustomPropertiesOk() ([]NameValueStringPairModel, bool) {
	if o == nil || IsNil(o.CustomProperties) {
		return nil, false
	}
	return o.CustomProperties, true
}

// HasCustomProperties returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasCustomProperties() bool {
	if o != nil && IsNil(o.CustomProperties) {
		return true
	}

	return false
}

// SetCustomProperties gets a reference to the given []NameValueStringPairModel and assigns it to the CustomProperties field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetCustomProperties(v []NameValueStringPairModel) {
	o.CustomProperties = v
}

// GetProvisioningSchemeName returns the ProvisioningSchemeName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetProvisioningSchemeName() string {
	if o == nil || IsNil(o.ProvisioningSchemeName.Get()) {
		var ret string
		return ret
	}
	return *o.ProvisioningSchemeName.Get()
}

// GetProvisioningSchemeNameOk returns a tuple with the ProvisioningSchemeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetProvisioningSchemeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProvisioningSchemeName.Get(), o.ProvisioningSchemeName.IsSet()
}

// HasProvisioningSchemeName returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasProvisioningSchemeName() bool {
	if o != nil && o.ProvisioningSchemeName.IsSet() {
		return true
	}

	return false
}

// SetProvisioningSchemeName gets a reference to the given NullableString and assigns it to the ProvisioningSchemeName field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetProvisioningSchemeName(v string) {
	o.ProvisioningSchemeName.Set(&v)
}
// SetProvisioningSchemeNameNil sets the value for ProvisioningSchemeName to be an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetProvisioningSchemeNameNil() {
	o.ProvisioningSchemeName.Set(nil)
}

// UnsetProvisioningSchemeName ensures that no value is present for ProvisioningSchemeName, not even an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) UnsetProvisioningSchemeName() {
	o.ProvisioningSchemeName.Unset()
}

// GetProvisioningSchemeId returns the ProvisioningSchemeId field value if set, zero value otherwise.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetProvisioningSchemeId() string {
	if o == nil || IsNil(o.ProvisioningSchemeId) {
		var ret string
		return ret
	}
	return *o.ProvisioningSchemeId
}

// GetProvisioningSchemeIdOk returns a tuple with the ProvisioningSchemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetProvisioningSchemeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProvisioningSchemeId) {
		return nil, false
	}
	return o.ProvisioningSchemeId, true
}

// HasProvisioningSchemeId returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasProvisioningSchemeId() bool {
	if o != nil && !IsNil(o.ProvisioningSchemeId) {
		return true
	}

	return false
}

// SetProvisioningSchemeId gets a reference to the given string and assigns it to the ProvisioningSchemeId field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetProvisioningSchemeId(v string) {
	o.ProvisioningSchemeId = &v
}

// GetVMId returns the VMId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetVMId() string {
	if o == nil || IsNil(o.VMId.Get()) {
		var ret string
		return ret
	}
	return *o.VMId.Get()
}

// GetVMIdOk returns a tuple with the VMId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetVMIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VMId.Get(), o.VMId.IsSet()
}

// HasVMId returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasVMId() bool {
	if o != nil && o.VMId.IsSet() {
		return true
	}

	return false
}

// SetVMId gets a reference to the given NullableString and assigns it to the VMId field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetVMId(v string) {
	o.VMId.Set(&v)
}
// SetVMIdNil sets the value for VMId to be an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetVMIdNil() {
	o.VMId.Set(nil)
}

// UnsetVMId ensures that no value is present for VMId, not even an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) UnsetVMId() {
	o.VMId.Unset()
}

// GetVMName returns the VMName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetVMName() string {
	if o == nil || IsNil(o.VMName.Get()) {
		var ret string
		return ret
	}
	return *o.VMName.Get()
}

// GetVMNameOk returns a tuple with the VMName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) GetVMNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VMName.Get(), o.VMName.IsSet()
}

// HasVMName returns a boolean if a field has been set.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) HasVMName() bool {
	if o != nil && o.VMName.IsSet() {
		return true
	}

	return false
}

// SetVMName gets a reference to the given NullableString and assigns it to the VMName field.
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetVMName(v string) {
	o.VMName.Set(&v)
}
// SetVMNameNil sets the value for VMName to be an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) SetVMNameNil() {
	o.VMName.Set(nil)
}

// UnsetVMName ensures that no value is present for VMName, not even an explicit nil
func (o *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) UnsetVMName() {
	o.VMName.Unset()
}

func (o ProvisionedVirtualMachineConfigurationResultantSetResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisionedVirtualMachineConfigurationResultantSetResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CpuCount.IsSet() {
		toSerialize["CpuCount"] = o.CpuCount.Get()
	}
	if o.MemoryMB.IsSet() {
		toSerialize["MemoryMB"] = o.MemoryMB.Get()
	}
	if !IsNil(o.MachineProfile) {
		toSerialize["MachineProfile"] = o.MachineProfile
	}
	if o.ServiceOffering.IsSet() {
		toSerialize["ServiceOffering"] = o.ServiceOffering.Get()
	}
	if o.CustomProperties != nil {
		toSerialize["CustomProperties"] = o.CustomProperties
	}
	if o.ProvisioningSchemeName.IsSet() {
		toSerialize["ProvisioningSchemeName"] = o.ProvisioningSchemeName.Get()
	}
	if !IsNil(o.ProvisioningSchemeId) {
		toSerialize["ProvisioningSchemeId"] = o.ProvisioningSchemeId
	}
	if o.VMId.IsSet() {
		toSerialize["VMId"] = o.VMId.Get()
	}
	if o.VMName.IsSet() {
		toSerialize["VMName"] = o.VMName.Get()
	}
	return toSerialize, nil
}

type NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel struct {
	value *ProvisionedVirtualMachineConfigurationResultantSetResponseModel
	isSet bool
}

func (v NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel) Get() *ProvisionedVirtualMachineConfigurationResultantSetResponseModel {
	return v.value
}

func (v *NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel) Set(val *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisionedVirtualMachineConfigurationResultantSetResponseModel(val *ProvisionedVirtualMachineConfigurationResultantSetResponseModel) *NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel {
	return &NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel{value: val, isSet: true}
}

func (v NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisionedVirtualMachineConfigurationResultantSetResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


