/*
Citrix Virtual Apps and Desktops REST API TECHPREVIEW

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: techpreview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the PolicyBodyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyBodyRequest{}

// PolicyBodyRequest Policy request model
type PolicyBodyRequest struct {
	// Policy name.
	Name *string `json:"name,omitempty"`
	// Is policy enabled
	IsEnabled bool `json:"isEnabled"`
	// Policy description
	Description *string `json:"description,omitempty"`
}

// NewPolicyBodyRequest instantiates a new PolicyBodyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyBodyRequest(isEnabled bool) *PolicyBodyRequest {
	this := PolicyBodyRequest{}
	this.IsEnabled = isEnabled
	return &this
}

// NewPolicyBodyRequestWithDefaults instantiates a new PolicyBodyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyBodyRequestWithDefaults() *PolicyBodyRequest {
	this := PolicyBodyRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PolicyBodyRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyBodyRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PolicyBodyRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PolicyBodyRequest) SetName(v string) {
	o.Name = &v
}

// GetIsEnabled returns the IsEnabled field value
func (o *PolicyBodyRequest) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *PolicyBodyRequest) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *PolicyBodyRequest) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PolicyBodyRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyBodyRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PolicyBodyRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PolicyBodyRequest) SetDescription(v string) {
	o.Description = &v
}

func (o PolicyBodyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyBodyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["isEnabled"] = o.IsEnabled
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullablePolicyBodyRequest struct {
	value *PolicyBodyRequest
	isSet bool
}

func (v NullablePolicyBodyRequest) Get() *PolicyBodyRequest {
	return v.value
}

func (v *NullablePolicyBodyRequest) Set(val *PolicyBodyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyBodyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyBodyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyBodyRequest(val *PolicyBodyRequest) *NullablePolicyBodyRequest {
	return &NullablePolicyBodyRequest{value: val, isSet: true}
}

func (v NullablePolicyBodyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyBodyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


