/*
Citrix Virtual Apps and Desktops Rest API for Developer Portal

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: devportal-onprem-ga
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the LogOperationSortCriteriaRequestModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogOperationSortCriteriaRequestModel{}

// LogOperationSortCriteriaRequestModel Log operation sort criteria.
type LogOperationSortCriteriaRequestModel struct {
	Property      LogOperationSearchProperty `json:"Property"`
	SortDirection ListSortDirection          `json:"SortDirection"`
}

// NewLogOperationSortCriteriaRequestModel instantiates a new LogOperationSortCriteriaRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogOperationSortCriteriaRequestModel(property LogOperationSearchProperty, sortDirection ListSortDirection) *LogOperationSortCriteriaRequestModel {
	this := LogOperationSortCriteriaRequestModel{}
	this.Property = property
	this.SortDirection = sortDirection
	return &this
}

// NewLogOperationSortCriteriaRequestModelWithDefaults instantiates a new LogOperationSortCriteriaRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogOperationSortCriteriaRequestModelWithDefaults() *LogOperationSortCriteriaRequestModel {
	this := LogOperationSortCriteriaRequestModel{}
	return &this
}

// GetProperty returns the Property field value
func (o *LogOperationSortCriteriaRequestModel) GetProperty() LogOperationSearchProperty {
	if o == nil {
		var ret LogOperationSearchProperty
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *LogOperationSortCriteriaRequestModel) GetPropertyOk() (*LogOperationSearchProperty, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *LogOperationSortCriteriaRequestModel) SetProperty(v LogOperationSearchProperty) {
	o.Property = v
}

// GetSortDirection returns the SortDirection field value
func (o *LogOperationSortCriteriaRequestModel) GetSortDirection() ListSortDirection {
	if o == nil {
		var ret ListSortDirection
		return ret
	}

	return o.SortDirection
}

// GetSortDirectionOk returns a tuple with the SortDirection field value
// and a boolean to check if the value has been set.
func (o *LogOperationSortCriteriaRequestModel) GetSortDirectionOk() (*ListSortDirection, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SortDirection, true
}

// SetSortDirection sets field value
func (o *LogOperationSortCriteriaRequestModel) SetSortDirection(v ListSortDirection) {
	o.SortDirection = v
}

func (o LogOperationSortCriteriaRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogOperationSortCriteriaRequestModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Property"] = o.Property
	toSerialize["SortDirection"] = o.SortDirection
	return toSerialize, nil
}

type NullableLogOperationSortCriteriaRequestModel struct {
	value *LogOperationSortCriteriaRequestModel
	isSet bool
}

func (v NullableLogOperationSortCriteriaRequestModel) Get() *LogOperationSortCriteriaRequestModel {
	return v.value
}

func (v *NullableLogOperationSortCriteriaRequestModel) Set(val *LogOperationSortCriteriaRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableLogOperationSortCriteriaRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableLogOperationSortCriteriaRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogOperationSortCriteriaRequestModel(val *LogOperationSortCriteriaRequestModel) *NullableLogOperationSortCriteriaRequestModel {
	return &NullableLogOperationSortCriteriaRequestModel{value: val, isSet: true}
}

func (v NullableLogOperationSortCriteriaRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogOperationSortCriteriaRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
