/*
Citrix Virtual Apps and Desktops Rest API for Developer Portal

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: devportal-onprem-ga
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the SearchFilter2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchFilter2{}

// SearchFilter2 Search filter for policies.
type SearchFilter2 struct {
	Property PolicyProperty `json:"Property"`
	// Value to match. For boolean properties this must be `\"true\"` or `\"false\"`. For string properties and enum values, this is case insensitive.
	Value string `json:"Value"`
	Operator SearchOperator `json:"Operator"`
}

// NewSearchFilter2 instantiates a new SearchFilter2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchFilter2(property PolicyProperty, value string, operator SearchOperator) *SearchFilter2 {
	this := SearchFilter2{}
	this.Property = property
	this.Value = value
	this.Operator = operator
	return &this
}

// NewSearchFilter2WithDefaults instantiates a new SearchFilter2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchFilter2WithDefaults() *SearchFilter2 {
	this := SearchFilter2{}
	return &this
}

// GetProperty returns the Property field value
func (o *SearchFilter2) GetProperty() PolicyProperty {
	if o == nil {
		var ret PolicyProperty
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *SearchFilter2) GetPropertyOk() (*PolicyProperty, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *SearchFilter2) SetProperty(v PolicyProperty) {
	o.Property = v
}

// GetValue returns the Value field value
func (o *SearchFilter2) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SearchFilter2) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SearchFilter2) SetValue(v string) {
	o.Value = v
}

// GetOperator returns the Operator field value
func (o *SearchFilter2) GetOperator() SearchOperator {
	if o == nil {
		var ret SearchOperator
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *SearchFilter2) GetOperatorOk() (*SearchOperator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *SearchFilter2) SetOperator(v SearchOperator) {
	o.Operator = v
}

func (o SearchFilter2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchFilter2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Property"] = o.Property
	toSerialize["Value"] = o.Value
	toSerialize["Operator"] = o.Operator
	return toSerialize, nil
}

type NullableSearchFilter2 struct {
	value *SearchFilter2
	isSet bool
}

func (v NullableSearchFilter2) Get() *SearchFilter2 {
	return v.value
}

func (v *NullableSearchFilter2) Set(val *SearchFilter2) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchFilter2) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchFilter2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchFilter2(val *SearchFilter2) *NullableSearchFilter2 {
	return &NullableSearchFilter2{value: val, isSet: true}
}

func (v NullableSearchFilter2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchFilter2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


