/*
Citrix Virtual Apps and Desktops REST API TECHPREVIEW

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: techpreview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the RefsRequestModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefsRequestModel{}

// RefsRequestModel Request object allowing caller to specify a list of object references, referenced by ID and/or Name.
type RefsRequestModel struct {
	// List of item references.
	Items []string `json:"Items"`
}

// NewRefsRequestModel instantiates a new RefsRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefsRequestModel(items []string) *RefsRequestModel {
	this := RefsRequestModel{}
	this.Items = items
	return &this
}

// NewRefsRequestModelWithDefaults instantiates a new RefsRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefsRequestModelWithDefaults() *RefsRequestModel {
	this := RefsRequestModel{}
	return &this
}

// GetItems returns the Items field value
func (o *RefsRequestModel) GetItems() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *RefsRequestModel) GetItemsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *RefsRequestModel) SetItems(v []string) {
	o.Items = v
}

func (o RefsRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefsRequestModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Items"] = o.Items
	return toSerialize, nil
}

type NullableRefsRequestModel struct {
	value *RefsRequestModel
	isSet bool
}

func (v NullableRefsRequestModel) Get() *RefsRequestModel {
	return v.value
}

func (v *NullableRefsRequestModel) Set(val *RefsRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableRefsRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableRefsRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefsRequestModel(val *RefsRequestModel) *NullableRefsRequestModel {
	return &NullableRefsRequestModel{value: val, isSet: true}
}

func (v NullableRefsRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefsRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


