/*
Citrix Virtual Apps and Desktops REST API TECHPREVIEW

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: techpreview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the ProvisioningSchemeResponseModelMachineAccountCreationRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisioningSchemeResponseModelMachineAccountCreationRules{}

// ProvisioningSchemeResponseModelMachineAccountCreationRules Machine account creation rules.
type ProvisioningSchemeResponseModelMachineAccountCreationRules struct {
	// The template name for AD accounts created in the identity pool.
	NamingScheme *string `json:"NamingScheme,omitempty"`
	NamingSchemeType *NamingSchemeType `json:"NamingSchemeType,omitempty"`
	// The OU that computer accounts will be created into.
	OU *string `json:"OU,omitempty"`
	Domain *MachineAccountCreationRulesResponseModelDomain `json:"Domain,omitempty"`
	// The next value that will be used if creating new AD accounts.
	NextValue *string `json:"NextValue,omitempty"`
}

// NewProvisioningSchemeResponseModelMachineAccountCreationRules instantiates a new ProvisioningSchemeResponseModelMachineAccountCreationRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisioningSchemeResponseModelMachineAccountCreationRules() *ProvisioningSchemeResponseModelMachineAccountCreationRules {
	this := ProvisioningSchemeResponseModelMachineAccountCreationRules{}
	return &this
}

// NewProvisioningSchemeResponseModelMachineAccountCreationRulesWithDefaults instantiates a new ProvisioningSchemeResponseModelMachineAccountCreationRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisioningSchemeResponseModelMachineAccountCreationRulesWithDefaults() *ProvisioningSchemeResponseModelMachineAccountCreationRules {
	this := ProvisioningSchemeResponseModelMachineAccountCreationRules{}
	return &this
}

// GetNamingScheme returns the NamingScheme field value if set, zero value otherwise.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetNamingScheme() string {
	if o == nil || IsNil(o.NamingScheme) {
		var ret string
		return ret
	}
	return *o.NamingScheme
}

// GetNamingSchemeOk returns a tuple with the NamingScheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetNamingSchemeOk() (*string, bool) {
	if o == nil || IsNil(o.NamingScheme) {
		return nil, false
	}
	return o.NamingScheme, true
}

// HasNamingScheme returns a boolean if a field has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) HasNamingScheme() bool {
	if o != nil && !IsNil(o.NamingScheme) {
		return true
	}

	return false
}

// SetNamingScheme gets a reference to the given string and assigns it to the NamingScheme field.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) SetNamingScheme(v string) {
	o.NamingScheme = &v
}

// GetNamingSchemeType returns the NamingSchemeType field value if set, zero value otherwise.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetNamingSchemeType() NamingSchemeType {
	if o == nil || IsNil(o.NamingSchemeType) {
		var ret NamingSchemeType
		return ret
	}
	return *o.NamingSchemeType
}

// GetNamingSchemeTypeOk returns a tuple with the NamingSchemeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetNamingSchemeTypeOk() (*NamingSchemeType, bool) {
	if o == nil || IsNil(o.NamingSchemeType) {
		return nil, false
	}
	return o.NamingSchemeType, true
}

// HasNamingSchemeType returns a boolean if a field has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) HasNamingSchemeType() bool {
	if o != nil && !IsNil(o.NamingSchemeType) {
		return true
	}

	return false
}

// SetNamingSchemeType gets a reference to the given NamingSchemeType and assigns it to the NamingSchemeType field.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) SetNamingSchemeType(v NamingSchemeType) {
	o.NamingSchemeType = &v
}

// GetOU returns the OU field value if set, zero value otherwise.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetOU() string {
	if o == nil || IsNil(o.OU) {
		var ret string
		return ret
	}
	return *o.OU
}

// GetOUOk returns a tuple with the OU field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetOUOk() (*string, bool) {
	if o == nil || IsNil(o.OU) {
		return nil, false
	}
	return o.OU, true
}

// HasOU returns a boolean if a field has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) HasOU() bool {
	if o != nil && !IsNil(o.OU) {
		return true
	}

	return false
}

// SetOU gets a reference to the given string and assigns it to the OU field.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) SetOU(v string) {
	o.OU = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetDomain() MachineAccountCreationRulesResponseModelDomain {
	if o == nil || IsNil(o.Domain) {
		var ret MachineAccountCreationRulesResponseModelDomain
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetDomainOk() (*MachineAccountCreationRulesResponseModelDomain, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given MachineAccountCreationRulesResponseModelDomain and assigns it to the Domain field.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) SetDomain(v MachineAccountCreationRulesResponseModelDomain) {
	o.Domain = &v
}

// GetNextValue returns the NextValue field value if set, zero value otherwise.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetNextValue() string {
	if o == nil || IsNil(o.NextValue) {
		var ret string
		return ret
	}
	return *o.NextValue
}

// GetNextValueOk returns a tuple with the NextValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) GetNextValueOk() (*string, bool) {
	if o == nil || IsNil(o.NextValue) {
		return nil, false
	}
	return o.NextValue, true
}

// HasNextValue returns a boolean if a field has been set.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) HasNextValue() bool {
	if o != nil && !IsNil(o.NextValue) {
		return true
	}

	return false
}

// SetNextValue gets a reference to the given string and assigns it to the NextValue field.
func (o *ProvisioningSchemeResponseModelMachineAccountCreationRules) SetNextValue(v string) {
	o.NextValue = &v
}

func (o ProvisioningSchemeResponseModelMachineAccountCreationRules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisioningSchemeResponseModelMachineAccountCreationRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NamingScheme) {
		toSerialize["NamingScheme"] = o.NamingScheme
	}
	if !IsNil(o.NamingSchemeType) {
		toSerialize["NamingSchemeType"] = o.NamingSchemeType
	}
	if !IsNil(o.OU) {
		toSerialize["OU"] = o.OU
	}
	if !IsNil(o.Domain) {
		toSerialize["Domain"] = o.Domain
	}
	if !IsNil(o.NextValue) {
		toSerialize["NextValue"] = o.NextValue
	}
	return toSerialize, nil
}

type NullableProvisioningSchemeResponseModelMachineAccountCreationRules struct {
	value *ProvisioningSchemeResponseModelMachineAccountCreationRules
	isSet bool
}

func (v NullableProvisioningSchemeResponseModelMachineAccountCreationRules) Get() *ProvisioningSchemeResponseModelMachineAccountCreationRules {
	return v.value
}

func (v *NullableProvisioningSchemeResponseModelMachineAccountCreationRules) Set(val *ProvisioningSchemeResponseModelMachineAccountCreationRules) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisioningSchemeResponseModelMachineAccountCreationRules) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisioningSchemeResponseModelMachineAccountCreationRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisioningSchemeResponseModelMachineAccountCreationRules(val *ProvisioningSchemeResponseModelMachineAccountCreationRules) *NullableProvisioningSchemeResponseModelMachineAccountCreationRules {
	return &NullableProvisioningSchemeResponseModelMachineAccountCreationRules{value: val, isSet: true}
}

func (v NullableProvisioningSchemeResponseModelMachineAccountCreationRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisioningSchemeResponseModelMachineAccountCreationRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


