/*
Citrix Virtual Apps and Desktops REST API TECHPREVIEW

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: techpreview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the LosingSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LosingSetting{}

// LosingSetting Settings that are not applied.
type LosingSetting struct {
	// Policy GUID.
	PolicyGuid *string `json:"PolicyGuid,omitempty"`
	// The policy that has the setting.
	PolicyName *string `json:"PolicyName,omitempty"`
	// The setting that is not applied.
	SettingName *string `json:"SettingName,omitempty"`
}

// NewLosingSetting instantiates a new LosingSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLosingSetting() *LosingSetting {
	this := LosingSetting{}
	return &this
}

// NewLosingSettingWithDefaults instantiates a new LosingSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLosingSettingWithDefaults() *LosingSetting {
	this := LosingSetting{}
	return &this
}

// GetPolicyGuid returns the PolicyGuid field value if set, zero value otherwise.
func (o *LosingSetting) GetPolicyGuid() string {
	if o == nil || IsNil(o.PolicyGuid) {
		var ret string
		return ret
	}
	return *o.PolicyGuid
}

// GetPolicyGuidOk returns a tuple with the PolicyGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LosingSetting) GetPolicyGuidOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyGuid) {
		return nil, false
	}
	return o.PolicyGuid, true
}

// HasPolicyGuid returns a boolean if a field has been set.
func (o *LosingSetting) HasPolicyGuid() bool {
	if o != nil && !IsNil(o.PolicyGuid) {
		return true
	}

	return false
}

// SetPolicyGuid gets a reference to the given string and assigns it to the PolicyGuid field.
func (o *LosingSetting) SetPolicyGuid(v string) {
	o.PolicyGuid = &v
}

// GetPolicyName returns the PolicyName field value if set, zero value otherwise.
func (o *LosingSetting) GetPolicyName() string {
	if o == nil || IsNil(o.PolicyName) {
		var ret string
		return ret
	}
	return *o.PolicyName
}

// GetPolicyNameOk returns a tuple with the PolicyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LosingSetting) GetPolicyNameOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyName) {
		return nil, false
	}
	return o.PolicyName, true
}

// HasPolicyName returns a boolean if a field has been set.
func (o *LosingSetting) HasPolicyName() bool {
	if o != nil && !IsNil(o.PolicyName) {
		return true
	}

	return false
}

// SetPolicyName gets a reference to the given string and assigns it to the PolicyName field.
func (o *LosingSetting) SetPolicyName(v string) {
	o.PolicyName = &v
}

// GetSettingName returns the SettingName field value if set, zero value otherwise.
func (o *LosingSetting) GetSettingName() string {
	if o == nil || IsNil(o.SettingName) {
		var ret string
		return ret
	}
	return *o.SettingName
}

// GetSettingNameOk returns a tuple with the SettingName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LosingSetting) GetSettingNameOk() (*string, bool) {
	if o == nil || IsNil(o.SettingName) {
		return nil, false
	}
	return o.SettingName, true
}

// HasSettingName returns a boolean if a field has been set.
func (o *LosingSetting) HasSettingName() bool {
	if o != nil && !IsNil(o.SettingName) {
		return true
	}

	return false
}

// SetSettingName gets a reference to the given string and assigns it to the SettingName field.
func (o *LosingSetting) SetSettingName(v string) {
	o.SettingName = &v
}

func (o LosingSetting) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LosingSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PolicyGuid) {
		toSerialize["PolicyGuid"] = o.PolicyGuid
	}
	if !IsNil(o.PolicyName) {
		toSerialize["PolicyName"] = o.PolicyName
	}
	if !IsNil(o.SettingName) {
		toSerialize["SettingName"] = o.SettingName
	}
	return toSerialize, nil
}

type NullableLosingSetting struct {
	value *LosingSetting
	isSet bool
}

func (v NullableLosingSetting) Get() *LosingSetting {
	return v.value
}

func (v *NullableLosingSetting) Set(val *LosingSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableLosingSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableLosingSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLosingSetting(val *LosingSetting) *NullableLosingSetting {
	return &NullableLosingSetting{value: val, isSet: true}
}

func (v NullableLosingSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLosingSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


