/*
Citrix Virtual Apps and Desktops Rest API for Developer Portal

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: devportal-onprem-ga
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package citrixorchestration

import (
	"encoding/json"
)

// checks if the ProvisioningSchemeSortCriteriaRequestModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisioningSchemeSortCriteriaRequestModel{}

// ProvisioningSchemeSortCriteriaRequestModel Provisioning scheme sort criteria.
type ProvisioningSchemeSortCriteriaRequestModel struct {
	Property      ProvisioningSchemeSearchProperty `json:"Property"`
	SortDirection ListSortDirection                `json:"SortDirection"`
}

// NewProvisioningSchemeSortCriteriaRequestModel instantiates a new ProvisioningSchemeSortCriteriaRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisioningSchemeSortCriteriaRequestModel(property ProvisioningSchemeSearchProperty, sortDirection ListSortDirection) *ProvisioningSchemeSortCriteriaRequestModel {
	this := ProvisioningSchemeSortCriteriaRequestModel{}
	this.Property = property
	this.SortDirection = sortDirection
	return &this
}

// NewProvisioningSchemeSortCriteriaRequestModelWithDefaults instantiates a new ProvisioningSchemeSortCriteriaRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisioningSchemeSortCriteriaRequestModelWithDefaults() *ProvisioningSchemeSortCriteriaRequestModel {
	this := ProvisioningSchemeSortCriteriaRequestModel{}
	return &this
}

// GetProperty returns the Property field value
func (o *ProvisioningSchemeSortCriteriaRequestModel) GetProperty() ProvisioningSchemeSearchProperty {
	if o == nil {
		var ret ProvisioningSchemeSearchProperty
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *ProvisioningSchemeSortCriteriaRequestModel) GetPropertyOk() (*ProvisioningSchemeSearchProperty, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *ProvisioningSchemeSortCriteriaRequestModel) SetProperty(v ProvisioningSchemeSearchProperty) {
	o.Property = v
}

// GetSortDirection returns the SortDirection field value
func (o *ProvisioningSchemeSortCriteriaRequestModel) GetSortDirection() ListSortDirection {
	if o == nil {
		var ret ListSortDirection
		return ret
	}

	return o.SortDirection
}

// GetSortDirectionOk returns a tuple with the SortDirection field value
// and a boolean to check if the value has been set.
func (o *ProvisioningSchemeSortCriteriaRequestModel) GetSortDirectionOk() (*ListSortDirection, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SortDirection, true
}

// SetSortDirection sets field value
func (o *ProvisioningSchemeSortCriteriaRequestModel) SetSortDirection(v ListSortDirection) {
	o.SortDirection = v
}

func (o ProvisioningSchemeSortCriteriaRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisioningSchemeSortCriteriaRequestModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Property"] = o.Property
	toSerialize["SortDirection"] = o.SortDirection
	return toSerialize, nil
}

type NullableProvisioningSchemeSortCriteriaRequestModel struct {
	value *ProvisioningSchemeSortCriteriaRequestModel
	isSet bool
}

func (v NullableProvisioningSchemeSortCriteriaRequestModel) Get() *ProvisioningSchemeSortCriteriaRequestModel {
	return v.value
}

func (v *NullableProvisioningSchemeSortCriteriaRequestModel) Set(val *ProvisioningSchemeSortCriteriaRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisioningSchemeSortCriteriaRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisioningSchemeSortCriteriaRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisioningSchemeSortCriteriaRequestModel(val *ProvisioningSchemeSortCriteriaRequestModel) *NullableProvisioningSchemeSortCriteriaRequestModel {
	return &NullableProvisioningSchemeSortCriteriaRequestModel{value: val, isSet: true}
}

func (v NullableProvisioningSchemeSortCriteriaRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisioningSchemeSortCriteriaRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
